<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Observatory.AgentRuntime\Observatory.AgentRuntime.csproj" />
    <PackageReference Include="A2A.AspNetCore" Version="0.3.4-preview" />
  </ItemGroup>

</Project>
